services:
  api:
    build: .
    platform: linux/amd64
    container_name: sentiment_dl_api
    ports:
      - "8080:8000"
    volumes:
      - ./saved_models:/workspace/saved_models
      - ./app:/workspace/app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - DATABASE_URL=postgresql://sentiment_user:sentiment_pass@db:5432/sentiment_db
      - REDIS_URL=redis://redis:6379/0
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    depends_on:
      - mlflow
      - db
      - redis
      - minio

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.10.2
    container_name: sentiment_mlflow
    ports:
      - "5001:5000"
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    volumes:
      - ./mlruns:/mlruns
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:////mlruns/mlflow.db
      --default-artifact-root s3://mlflow/
    depends_on:
      - minio_create_bucket

  prometheus:
    image: prom/prometheus:latest
    container_name: sentiment_prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml:ro

  alertmanager:
    image: prom/alertmanager:latest
    container_name: sentiment_alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: sentiment_grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  frontend:
    build: ./frontend
    container_name: sentiment_react_ui
    ports:
      - "4000:3000"
    depends_on:
      - api

  db:
    image: postgres:15-alpine
    container_name: sentiment_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sentiment_user
      - POSTGRES_PASSWORD=sentiment_pass
      - POSTGRES_DB=sentiment_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: sentiment_redis
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: sentiment_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data

  minio_create_bucket:
    image: minio/mc
    container_name: sentiment_minio_bucket_creator
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/mlflow --ignore-existing;
      exit 0;
      "

  evidently_ui:
    image: python:3.10
    container_name: sentiment_evidently_ui
    ports:
      - "8001:8000"
    volumes:
      - ./evidently_workspace:/workspace
    working_dir: /workspace
    command: >
      bash -c "pip install --upgrade pip && pip install evidently fastapi uvicorn && evidently ui --host 0.0.0.0 --port 8000 --workspace /workspace"
