route:
  receiver: 'telegram_bot'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h

receivers:
- name: 'telegram_bot'
  telegram_configs:
  - bot_token: '8634667672:AAEtiE5bMt52NrCBrJ1MB_7UHH5-G_b0kVE'
    api_url: 'https://api.telegram.org'
    chat_id: 8569010173
    parse_mode: 'HTML'
    message: |
      🚨 <b>CẢNH BÁO MLOPS HỆ THỐNG</b> 🚨
      
      <b>Tình trạng:</b> {{ .Status | toUpper }}
      <b>Lỗi:</b> {{ .GroupLabels.alertname }}
      
      <b>Chi tiết:</b>
      {{ range .Alerts }}
      • <b>Mô tả:</b> {{ .Annotations.description }}
      • <b>Mức độ:</b> {{ .Labels.severity }}
      • <b>Phát hiện lúc:</b> {{ .StartsAt.Format "2006-01-02 15:04:05" }}
      {{ end }}
